// File: memory.v
// Generated by MyHDL 0.11
// Date: Wed Oct 13 23:39:16 2021


`timescale 1ns/10ps

module memory (
    addres,
    data_in,
    enable,
    clk,
    data_out
);


input [4:0] addres;
input [31:0] data_in;
input enable;
input clk;
output [31:0] data_out;
reg [31:0] data_out;

reg [31:0] memory32 [0:32-1];



always @(posedge clk) begin: MEMORY_WRITE
    if ((enable == 1)) begin
        memory32[addres] <= data_in;
    end
    data_out <= memory32[addres];
end

endmodule
