// File: mux_3to1.v
// Generated by MyHDL 0.11
// Date: Sun Oct  3 04:54:56 2021


`timescale 1ns/10ps

module mux_3to1 (
    i0,
    i1,
    i2,
    sel,
    out
);


input [0:0] i0;
input [0:0] i1;
input [0:0] i2;
input [1:0] sel;
output [0:0] out;
reg [0:0] out;




always @(sel, i2, i0, i1) begin: MUX_3TO1_MUX3TO1
    if ((sel == 0)) begin
        out = i0;
    end
    if ((sel == 1)) begin
        out = i1;
    end
    if ((sel == 2)) begin
        out = i2;
    end
    if ((sel == 3)) begin
        out = i2;
    end
end

endmodule
