// File: decoder.v
// Generated by MyHDL 0.11
// Date: Sun Oct 17 18:43:05 2021


`timescale 1ns/10ps

module decoder (
    din,
    dout
);


input [3:0] din;
output [15:0] dout;
reg [15:0] dout;




always @(din) begin: DECODER_DECODER_4TO16
    case (din)
        'h0: begin
            dout = 1;
        end
        'h1: begin
            dout = 2;
        end
        'h2: begin
            dout = 4;
        end
        'h3: begin
            dout = 8;
        end
        'h4: begin
            dout = 16;
        end
        'h5: begin
            dout = 32;
        end
        'h6: begin
            dout = 64;
        end
        'h7: begin
            dout = 128;
        end
        'h8: begin
            dout = 256;
        end
        'h9: begin
            dout = 512;
        end
        'ha: begin
            dout = 1024;
        end
        'hb: begin
            dout = 2048;
        end
        'hc: begin
            dout = 4096;
        end
        'hd: begin
            dout = 8192;
        end
        'he: begin
            dout = 16384;
        end
        default: begin
            dout = 32768;
        end
    endcase
end

endmodule
