// File: decoder.v
// Generated by MyHDL 0.11
// Date: Sun Oct  3 05:17:39 2021


`timescale 1ns/10ps

module decoder (
    i0,
    i1,
    i2,
    i3,
    d0,
    d1,
    d2,
    d3,
    d4,
    d5,
    d6,
    d7,
    d8,
    d9,
    d10,
    d11,
    d12,
    d13,
    d14,
    d15
);


input [0:0] i0;
input [0:0] i1;
input [0:0] i2;
input [0:0] i3;
output [0:0] d0;
wire [0:0] d0;
output [0:0] d1;
wire [0:0] d1;
output [0:0] d2;
wire [0:0] d2;
output [0:0] d3;
wire [0:0] d3;
output [0:0] d4;
wire [0:0] d4;
output [0:0] d5;
wire [0:0] d5;
output [0:0] d6;
wire [0:0] d6;
output [0:0] d7;
wire [0:0] d7;
output [0:0] d8;
wire [0:0] d8;
output [0:0] d9;
wire [0:0] d9;
output [0:0] d10;
wire [0:0] d10;
output [0:0] d11;
wire [0:0] d11;
output [0:0] d12;
wire [0:0] d12;
output [0:0] d13;
wire [0:0] d13;
output [0:0] d14;
wire [0:0] d14;
output [0:0] d15;
wire [0:0] d15;





assign d0 = ((((~i3) & (~i2)) & (~i1)) & (~i0));
assign d1 = ((((~i3) & (~i2)) & (~i1)) & i0);
assign d2 = ((((~i3) & (~i2)) & i1) & (~i0));
assign d3 = ((((~i3) & (~i2)) & i1) & i0);
assign d4 = ((((~i3) & i2) & (~i1)) & (~i0));
assign d5 = ((((~i3) & i2) & (~i1)) & i0);
assign d6 = ((((~i3) & i2) & i1) & (~i0));
assign d7 = ((((~i3) & i2) & i1) & i0);
assign d8 = (((i3 & (~i2)) & (~i1)) & (~i0));
assign d9 = (((i3 & (~i2)) & (~i1)) & i0);
assign d10 = (((i3 & (~i2)) & i1) & (~i0));
assign d11 = (((i3 & (~i2)) & i1) & i0);
assign d12 = (((i3 & i2) & (~i1)) & (~i0));
assign d13 = (((i3 & i2) & (~i1)) & i0);
assign d14 = (((i3 & i2) & i1) & (~i0));
assign d15 = (((i3 & i2) & i1) & i0);

endmodule
